spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/big-event?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
mybatis:
  config-location: